import { PERMISSIONS, type PermissionKey, ALL_PERMISSIONS } from './permissions';

export const ROLE_KEYS = {
  OWNER: 'OWNER',
  SYS_ADMIN: 'SYS_ADMIN',
  BRANCH_MANAGER: 'BRANCH_MANAGER',
  CASHIER: 'CASHIER',
  TECHNICIAN: 'TECHNICIAN',
  ACCOUNTANT: 'ACCOUNTANT',
} as const;

export type RoleKey = (typeof ROLE_KEYS)[keyof typeof ROLE_KEYS];

const P = PERMISSIONS;

/**
 * Default permission sets per system role. OWNER gets every permission.
 * Branch scoping (own-branch-only) is enforced separately via UserRole.branchIds.
 */
export const ROLE_PERMISSIONS: Record<RoleKey, PermissionKey[]> = {
  OWNER: [...ALL_PERMISSIONS],

  SYS_ADMIN: ALL_PERMISSIONS.filter(
    (p) => p !== P.SETTINGS_BILLING, // subscription/billing of the SaaS itself is owner-only
  ),

  BRANCH_MANAGER: [
    P.BRANCH_READ,
    P.ROOM_READ, P.ROOM_MANAGE, P.FLOORPLAN_MANAGE,
    P.COMPUTER_READ, P.COMPUTER_MANAGE, P.COMPUTER_REMOTE_CONTROL,
    P.COMPUTER_REMOTE_SCREENSHOT, P.COMPUTER_GROUP_MANAGE, P.AGENT_INSTALL, P.AGENT_UPDATE,
    P.CUSTOMER_READ, P.CUSTOMER_CREATE, P.CUSTOMER_UPDATE, P.CUSTOMER_BLOCK,
    P.CUSTOMER_MERGE, P.CUSTOMER_DELETE, P.CUSTOMER_GROUP_MANAGE,
    P.ACCESS_PROFILE_READ, P.ACCESS_PROFILE_MANAGE,
    P.BALANCE_READ, P.BALANCE_LOAD, P.BALANCE_TRANSFER, P.BALANCE_ADJUST,
    P.PACKAGE_READ, P.PRICING_READ, P.COUPON_MANAGE,
    P.SESSION_READ, P.SESSION_OPEN, P.SESSION_CLOSE, P.SESSION_MODIFY, P.SESSION_TRANSFER,
    P.RESERVATION_READ, P.RESERVATION_MANAGE,
    P.PRINT_READ, P.PRINT_APPROVE, P.PRINT_MANAGE, P.PRINTER_MANAGE,
    P.SALE_CREATE, P.SALE_READ, P.PAYMENT_TAKE, P.REFUND_CREATE,
    P.CASH_SHIFT_OPEN, P.CASH_SHIFT_CLOSE, P.CASH_MOVEMENT_CREATE, P.INVOICE_ISSUE,
    P.MAINTENANCE_READ, P.MAINTENANCE_MANAGE, P.EQUIPMENT_MANAGE,
    P.EMPLOYEE_READ,
    P.REPORT_REVENUE, P.REPORT_USAGE, P.REPORT_PRINT, P.REPORT_SYSTEM, P.REPORT_EXPORT,
    P.NOTIFICATION_READ, P.NOTIFICATION_SEND,
    P.CONSENT_MANAGE, P.DOCUMENT_MANAGE,
    P.AUDIT_READ,
  ],

  CASHIER: [
    P.BRANCH_READ,
    P.COMPUTER_READ,
    P.CUSTOMER_READ, P.CUSTOMER_CREATE, P.CUSTOMER_UPDATE,
    P.ACCESS_PROFILE_READ,
    P.BALANCE_READ, P.BALANCE_LOAD,
    P.PACKAGE_READ, P.PRICING_READ,
    P.SESSION_READ, P.SESSION_OPEN, P.SESSION_CLOSE, P.SESSION_MODIFY, P.SESSION_TRANSFER,
    P.RESERVATION_READ,
    P.PRINT_READ, P.PRINT_APPROVE,
    P.SALE_CREATE, P.SALE_READ, P.PAYMENT_TAKE,
    P.CASH_SHIFT_OPEN, P.CASH_SHIFT_CLOSE, P.CASH_MOVEMENT_CREATE, P.INVOICE_ISSUE,
    P.NOTIFICATION_READ,
  ],

  TECHNICIAN: [
    P.BRANCH_READ,
    P.COMPUTER_READ, P.COMPUTER_MANAGE, P.COMPUTER_REMOTE_CONTROL, P.AGENT_UPDATE,
    P.MAINTENANCE_READ, P.MAINTENANCE_MANAGE, P.EQUIPMENT_MANAGE,
    P.REPORT_SYSTEM,
    P.NOTIFICATION_READ,
  ],

  ACCOUNTANT: [
    P.BRANCH_READ,
    P.SALE_READ,
    P.REPORT_REVENUE, P.REPORT_USAGE, P.REPORT_PRINT, P.REPORT_EXPORT,
  ],
};

export const SYSTEM_ROLE_NAMES: Record<RoleKey, string> = {
  OWNER: 'בעלים',
  SYS_ADMIN: 'מנהל מערכת',
  BRANCH_MANAGER: 'מנהל סניף',
  CASHIER: 'עובד קופה',
  TECHNICIAN: 'טכנאי',
  ACCOUNTANT: 'רואה חשבון',
};
